version: '3.7'

services:
  emulator:
    image: 'pubsub-emulator:latest'
    build:
      context: .
    environment:
      - PUBSUB_PROJECT_ID=${PUBSUB_PROJECT_ID}
      - PUBSUB_TOPIC_ID=${PUBSUB_TOPIC_ID}
    ports:
      - '8432:8432'
